#!/bin/bash

mkdir -p /usr/src/ethereumDB

# Fix permissions on ethererum directory.
chmod -R o+rwx /usr/src/ethereumDB

# Add our main account in charge of the ballots.
geth --datadir /usr/src/ethereumDB \
     --password $WORK_DIR/ethereum/keys/ethereum_password account import $WORK_DIR/ethereum/keys/ethereum_private_key

# For unlocking our account
account_address=$(cat $WORK_DIR/ethereum/keys/ethereum_address)

# Start geth in background
geth --datadir /usr/src/ethereumDB --fast --cache=1024 \
     --unlock $account_address --password $WORK_DIR/ethereum/keys/ethereum_password \
     2> /usr/src/ethereumDB/geth.log &
