# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_ballot_registration', '0002_auto_20170315_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_id', models.IntegerField()),
                ('voter_address', models.CharField(max_length=1000)),
                ('voter_private_key', models.CharField(max_length=1000)),
                ('voter_public_key', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registeraddress',
            unique_together=set([('user', 'ballot_id')]),
        ),
    ]
