# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='initial_login',
            new_name='force_enterDetails',
        ),
    ]
