# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170305_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='force_enterDetails',
            field=models.BooleanField(default=True),
        ),
    ]
