# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170311_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.IntegerField(unique=True),
        ),
    ]
