#!/bin/bash

##################################################
#
# Retrieve the name of the docker application server
# and send it the parameters as a command.
#
##################################################

APPLICATIONSERVER_NAME=$(docker ps | grep applicationserver | grep -oE '[^ ]+$')

docker exec -i -t $APPLICATIONSERVER_NAME $@
