#!/bin/bash

##################################################
#
# Retrieve the name of the docker onlineaccountverifier
# and send it the parameters as a command.
#
##################################################

APPLICATIONSERVER_NAME=$(docker ps | grep onlineaccountverifier | grep -oE '[^ ]+$')

docker exec -i -t $APPLICATIONSERVER_NAME "$@"
